user_token: NmE0YzRjMzEtNTM2Zi00NDY5LThmNzItZTE1YmE2MTZkNGE4XzEyNTQ=

session:
  key: 
admin:
  email: admin@admin.com
  password: 
database:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: 
  database: postgres
bot:
  token: 
  group_id: 


