version: "3.9"

services:
  postgresdb:
    image: postgres
    environment: 
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432

  blackjack:
    build: .
    network_mode: "host"


