"""First

Revision ID: fb5d4d795899
Revises:
Create Date: 2023-01-03 20:42:52.439587

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fb5d4d795899"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Unicode(), nullable=True),
        sa.Column("password", sa.Unicode(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=True),
        sa.Column(
            "deck",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=False,
        ),
        sa.Column("state", sa.Unicode(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("vk_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Unicode(), nullable=True),
        sa.Column("info", sa.Unicode(), nullable=True),
        sa.Column("num_of_wins", sa.Integer(), nullable=False),
        sa.Column("cash", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("vk_id"),
    )
    op.create_table(
        "player",
        sa.Column("vk_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column(
            "cards",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=False,
        ),
        sa.Column("bet", sa.Float(), nullable=True),
        sa.Column("state", sa.Unicode(), nullable=False),
        sa.ForeignKeyConstraint(["table_id"], ["table.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player")
    op.drop_table("user")
    op.drop_table("table")
    op.drop_table("admins")
    # ### end Alembic commands ###
